insert into questions (subject) values ("Hewan yang boleh dijadikan sebagai hewan kurban adalah sebagai berikut..");
insert into questions (subject) values ("Hukum berkurban menurut Jumhur Ulama’ adalah..");
insert into questions (subject) values ("Secara Umum, hewan yang sah untuk dijadikan hewan kurban harus memenuhi syarat berikut..");
insert into questions (subject) values ("Dalil dari Al-Quran tentang anjuran berkurban adalah..");
insert into questions (subject) values ("Seseorang menyembelih hewan kurbannya pada waktu sebelum berangkat sholat Ied. Maka hukumnya adalah..");
insert into questions (subject) values ("Rukun menyembelih diantaranya adalah..");
insert into questions (subject) values ("Diantara larangan dalam menyembelih yang disebutkan dalam Hadits adalah..");
insert into questions (subject) values ("Yang berhak menerima pembagian daging kurban adalah..");
insert into questions (subject) values ("Berkaitan dengan daging kurban, yang tidak boleh dilakukan adalah..");
insert into questions (subject) values ("Merebahkan hewan kurban pada lambung kiri dan menghadap kiblat termasuk..");
insert into questions (subject) values ("Diantara tujuan handling hewan yang akan disembelih adalah");
insert into questions (subject) values ("Perlengkapan utama dalam proses handling adalah..");
insert into questions (subject) values ("Pada kegiatan Idul Adha, proses handling dimulai saat..");
insert into questions (subject) values ("Diantara penyebab sapi stress dan agresif adalah karena..");
insert into questions (subject) values ("Proses handling sapi idealnya dilakukan oleh petugas berjumlah.....	");
insert into questions (subject) values ("Perobohan sapi yang dinilai ihsan bagi hewan misalnya dengan metode..");
insert into questions (subject) values ("Untuk mengurangi kemungkinan sapi lepas saat ditambat di lokasi eksekusi..");
insert into questions (subject) values ("Saat mengikat kaki sapi, posisi petugas yang paling beresiko (berbahaya) adalah..");
insert into questions (subject) values ("Sebelum menyembelih, yang perlu diperhatikan seorang Juru Sembelih..");
insert into questions (subject) values ("Tali yang direkomendasikan untuk merobohkan sapi adalah..");
insert into questions (subject) values ("Halalnya hewan yang disembelih ditinjau dari syarat penyembelihnya, kecuali..");
insert into questions (subject) values ("Menyembelih hewan untuk dipersembahkan sebagai sesajen kepada penunggu jembatan hukumnya..");
insert into questions (subject) values ("Ketika menyembelih, yang terpotong hanya Hulqum dan Mari’, maka hukumnya..");
insert into questions (subject) values ("Teknik menyembelih yang umum digunakan adalah..");
insert into questions (subject) values ("Posisi sayatan yang ideal untuk menyembelih kambing adalah..");
insert into questions (subject) values ("Menyembelih ayam sampai putus lehernya, hukumnya..");
insert into questions (subject) values ("Yang pertama kali harus dilakukan seorang juru sembelih setelah menyembelih adalah..");
insert into questions (subject) values ("Dalam proses penyembelihan, sapi dinaiki banyak orang agar tidak berontak. Hal tersebut termasuk..	");
insert into questions (subject) values ("Yang boleh dilakukan terhadap hewan sesaat setelah disembelih adalah..");
insert into questions (subject) values ("Diantara larangan ketika akan menyembelih adalah..");
insert into questions (subject) values ("Berkaitan dengan alat sembelih, yang dilarang oleh Syariat adalah..");
insert into questions (subject) values ("Syarat minimal untuk pisau sembelih adalah..");
insert into questions (subject) values ("Salah satu cara mengecek kematian hewan adalah..");
insert into questions (subject) values ("Jika hewan belum mati sempurna maka yang dilakukan adalah..");
insert into questions (subject) values ("Diantara adab yang harus diperhatikan seorang juru sembelih adalah..");
insert into questions (subject) values ("Diantara fungsi APD adalah..");
insert into questions (subject) values ("Yang hendaknya memakai APD adalah..");
insert into questions (subject) values ("Salah satu contoh APD adalah..");
insert into questions (subject) values ("APD yang berfungsi untuk melindungi dari terkena sayatan pisau adalah..");
insert into questions (subject) values ("Salah satu alasan memakai sepatu boot karet adalah..");
insert into questions (subject) values ("Gambar di bawah ini termasuk jenis..");
insert into questions (subject) values ("Gambar di bawah ini termasuk jenis..");
insert into questions (subject) values ("Agar tajam, maka pisau sembelih harus..");
insert into questions (subject) values ("Media asah yang banyak dipakai masyarakat pada umumnya adalah..");
insert into questions (subject) values ("Gambar berikut termasuk jenis batu asah......	");
insert into questions (subject) values ("Salah satu kunci keberhasilan mengasah adalah..");
insert into questions (subject) values ("Salah satu metode mengetes ketajaman pisau sembelih adalah..");
insert into questions (subject) values ("Cara menjaga ketajaman pisau sembelih pada saat di lapangan diantaranya..");
insert into questions (subject) values ("Salah satu sebab berkurangnya ketajaman pisau sembelih adalah..");
insert into questions (subject) values ("Apabila pisau sembelih yang dipakai di lapangan sudah kurang tajam, maka..");
